//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Details
    {
        public int Bank_ID { get; set; }
        public string Bank { get; set; }
        public string Org { get; set; }
        public string Branch { get; set; }
        public Nullable<long> Account { get; set; }
    }
}
