//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public int Date_ID { get; set; }
        public int Datekey { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string MonthYear { get; set; }
        public Nullable<short> DayOfYear { get; set; }
        public Nullable<byte> DayNo { get; set; }
        public string DateName { get; set; }
        public Nullable<int> BusinessDayNo { get; set; }
        public Nullable<byte> DayOfWeek { get; set; }
        public string WeekDayName { get; set; }
        public Nullable<byte> WeekNo { get; set; }
        public Nullable<byte> WeekOfMonth { get; set; }
        public Nullable<byte> DOWInMonth { get; set; }
        public Nullable<byte> WeekOfYear { get; set; }
        public Nullable<byte> ISOWeekOfYear { get; set; }
        public Nullable<byte> Month { get; set; }
        public string MonthName { get; set; }
        public Nullable<byte> QuarterNo { get; set; }
        public string QuarterName { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> FirstDayofWeek { get; set; }
        public Nullable<System.DateTime> LastDayofWeek { get; set; }
        public Nullable<System.DateTime> FirstDayOfMonth { get; set; }
        public Nullable<System.DateTime> LastDayOfMonth { get; set; }
        public Nullable<System.DateTime> FirstDayOfQuarter { get; set; }
        public Nullable<System.DateTime> LastDayOfQuarter { get; set; }
        public Nullable<System.DateTime> FirstDayOfYear { get; set; }
        public Nullable<System.DateTime> LastDayOfYear { get; set; }
        public Nullable<System.DateTime> FirstDayOfNextMonth { get; set; }
        public Nullable<System.DateTime> FirstDayOfNextYear { get; set; }
        public Nullable<byte> IsWeekend { get; set; }
        public Nullable<byte> IsHoliday { get; set; }
        public string HolidayDescription { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
