//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashPaymentVoucher
    {
        public int id { get; set; }
        public string Vnumber { get; set; }
        public string Date { get; set; }
        public string PaidTo { get; set; }
        public string Control { get; set; }
        public string Category { get; set; }
        public Nullable<long> Amount { get; set; }
        public string Description { get; set; }
        public string Rupees { get; set; }
        public string filterDate { get; set; }
        public Nullable<System.DateTime> createAT { get; set; }
        public Nullable<bool> isPending { get; set; }
        public Nullable<bool> isCancel { get; set; }
    }
}
