//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashReceiptVoucher
    {
        public int ID { get; set; }
        public Nullable<int> VNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Received_From { get; set; }
        public string Category { get; set; }
        public string A_C_Description { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Rupees { get; set; }
        public string Narration { get; set; }
    }
}
