//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientRef { get; set; }
        public string ClientCity { get; set; }
        public string ClientPhone { get; set; }
        public string ClientAddress { get; set; }
    }
}
