//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payable
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public string Supplier_Other { get; set; }
        public string Payment_Against { get; set; }
        public string Comapny { get; set; }
        public string Department { get; set; }
        public string Expense { get; set; }
        public string Bank_Cash { get; set; }
        public Nullable<decimal> Bill_Amount { get; set; }
        public string Tax_Rate { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Ref_Inst_Nos { get; set; }
        public string Ref_V_Type { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
        public Nullable<System.DateTime> updateAT { get; set; }
    }
}
