//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recievable
    {
        public int id { get; set; }
        public string name { get; set; }
        public string GlCode { get; set; }
        public string number_Instrument { get; set; }
        public string Date_Instrument { get; set; }
        public string bank_Instrument { get; set; }
        public string company { get; set; }
        public string department { get; set; }
        public Nullable<long> invoice_amount { get; set; }
        public string rate { get; set; }
        public Nullable<int> tax { get; set; }
        public Nullable<int> wst { get; set; }
        public Nullable<long> totalAmount { get; set; }
        public string bank_cash_ToBeDepositedvarchar { get; set; }
        public string date_ToBeDeposited { get; set; }
        public string comments { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> creatAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
    }
}
